SECTION TEXT
MUL_N: MACRO 
MULT N
STORE N
ENDMACRO
INPUT N
LOAD N
FAT: SUB ONE
JMPZ FIM
STORE: STORE AUX ; Error: LABEL_RESERVED
MUL_N 
FAT: LOAD AUX ; Error: LABEL_REDECLARED
JMP FAT
FIM: OUTPUT N
STOP
SECTION DATA
AUX: SPACE
N: SPACE
ONE: CONST 1

ERR1: JMP   _1    ; Error: UNRESOLVED_SYMBOL
ERR2: CONST SPACE ; Error: ILLEGAL_PARAM
ERR3: CONST       ; Error: UNEXPECTED_EOF