BEGIN
SECTION TEXT
MOD_B:	BEGIN
VAL:	EXTERN
L1:	EXTERN
	PUBLIC Y
	PUBLIC MOD_B
	OUTPUT Y      ; 0, 1
	OUTPUT VAL    ; 2, 3
	OUTPUT Y      ; 4, 5
	JMP L1        ; 6, 7
SECTION DATA
Y:	SPACE 3       ; 8
END